-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "createAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "createAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "File" ADD COLUMN     "createAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updateAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateAt" SET DEFAULT CURRENT_TIMESTAMP;
